# Generated by Django 5.2.11 on 2026-02-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="Endereço"),
        ),
    ]
