# Generated by Django 5.2.11 on 2026-02-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default="PED-DEFAULT0",
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Número do Pedido",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderhistory",
            name="changed_by",
            field=models.CharField(
                blank=True,
                default="system",
                max_length=100,
                verbose_name="Usuário Responsável",
            ),
        ),
    ]
